# Generated by Django 2.2 on 2021-09-30 09:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320, verbose_name='Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(verbose_name='Date end')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rate', models.CharField(max_length=100, verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('date_birth', models.DateField(verbose_name='Birth day')),
                ('office', models.CharField(max_length=100, verbose_name='Office')),
                ('date_acceptance', models.DateField(verbose_name='Date of acceptance')),
                ('date_dismissal', models.DateField(blank=True, null=True, verbose_name='Date of dismissal')),
                ('is_working', models.BooleanField(verbose_name='is it working?')),
                ('time_working', models.TimeField(verbose_name='Working time')),
                ('time_reception', models.TimeField(verbose_name='Reception time')),
                ('date_contract_end', models.DateField(verbose_name='Contract completion date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Category', verbose_name='Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Department', verbose_name='Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Position', verbose_name='Position')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Specialization', verbose_name='Specialization')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='PersonalRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(max_length=100, verbose_name='Row type')),
                ('row_data', models.CharField(max_length=320, verbose_name='Row data')),
                ('date', models.DateField(verbose_name='Date')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Experience', verbose_name='Experience')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Personal row',
                'verbose_name_plural': 'Personal rows',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320, verbose_name='Name')),
                ('desc', models.CharField(max_length=320, verbose_name='Description')),
                ('filename', models.FileField(upload_to='', verbose_name='File')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='Staff'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(max_length=100, verbose_name='Type')),
                ('education_value', models.CharField(max_length=320, verbose_name='Value')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Specialization', verbose_name='Specialization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to='hr.Staff', verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.Department'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'E-mail')], default=1, max_length=100, verbose_name='Type')),
                ('contact_value', models.CharField(max_length=100, verbose_name='Value')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
